spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/stockify_management_db
        username: admin
        password: admin123
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8081